name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
env:
  CRYPTOGRAPHY_DONT_BUILD_RUST: 1

jobs:
  build:
    runs-on: ubuntu-16.04
    container: python:3.6-alpine

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: apk --update --no-cache add gcc libc-dev libffi-dev openssl-dev

    - name: Install pybuilder
      run: pip install pybuilder

    - name: Install dependencies
      run: pyb install_dependencies

    - name: Execute build
      run: pyb install

    - name: Install Codecov requirements
      run: |
        apk update
        apk add bash curl
        sed -e 's,filename="pybuilder-radon/,filename="src/main/python/pybuilder_radon/,g' target/reports/coverage.xml > coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml

